#apiVersion: v1
#kind: Secret
#metadata:
#  name: "{{ .Release.Name  }}-configs"
#type: Opaque
#data:
#  {{- range $index, $value := .Values.configurations }}
#    {{ $index }}: {{ $value | b64enc }}
#  {{- end }}
#
#------------------
apiVersion: v1
kind: Secret
metadata:
  name: "IAM_CREDENTIALS"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.awsAccessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.awsSecretAccessKey }}