# Default values for capillary-base-statefulset.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
serviceType: LoadBalancer

resources: {}

tolerations: []

affinity: {}

hpaEnabled: "true"


