repos:
- repo: local
  hooks:
    - id: create-json-service-fix
      name: create-json-service-fix
      entry: bash -c 'echo "{}" > capillary-cloud-tf/modules/1_input_instance/deploymentcontext.json'
      language: system
      pass_filenames: false
    - id: create-json-service-dir
      name: create-json-service-dir
      entry: bash -c 'echo "{}" > capillary-cloud-tf/modules/3_utility/deploymentcontext.json'
      language: system
      pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: forbid-new-submodules

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args:
        - --markdown-linebreak-ext=md
    - id: check-yaml
      exclude: '.*\/templates\/'
    - id: check-json
    - id: pretty-format-json
      args:
        - --autofix
        - --no-sort-keys

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args:
        - --fix=lf

    # Security
    - id: detect-aws-credentials
      args:
        - --allow-missing-credentials
    - id: detect-private-key

-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
      - id: go-fmt
        args:
        - -w

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.74.2
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
      exclude: '^[^/]+$'
