pipelines:
  branches:
    tf_0.13_upgradenew:
      - step:
         script:
          - echo "hi"
          - apt-get update && apt-get install git -y
          - pip3 install git-filter-repo
          - ls -a
          - git filter-repo --force --path capillary-cloud-tf
          - git remote add github git@github.com:Facets-cloud/facets-iac.git
          - git push github:tf_0.13_upgradenew