pipelines:
  branches:
    tf_0.13_upgradenew:
      - step:
         script:
          - apt-get update && apt-get install git -y
          - git remote add github git@github.com:Facets-cloud/facets-iac.git
          - git push github:tf_0.13_upgradenew