USER-SUPPLIED VALUES:
mysql:
  host: tatacrmmetadb.cluster-ro-cimtmxy7e7iy.ap-south-1.rds.amazonaws.com
  pass: pjhkrj9gLa7p
  user: root
serviceMonitor:
  enabled: true
collectors:
  slave_hosts: true
  perf_schema.replication_group_member_stats: true
