apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name  }}-configs"
type: Opaque
data:
  {{- range $index, $value := .Values.configurations }}
    {{ $index }}: {{ $value | b64enc }}
  {{- end }}