apiVersion: v1
appVersion: "1.0"
description: Provide IAM credentials to pods based on annotations.
engine: gotpl
home: https://github.com/jtblin/kube2iam
name: kube2iam
sources:
- https://github.com/jtblin/kube2iam
version: 1.0.1
