{{- $releaseName := .Release.Name}}
{{- $crmModuleName := .Values.crmModuleName}}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name  }}
  labels:
    app: {{ .Release.Name  }}
    chart: {{ template "capillary-base-cronjob.chart" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          concurrencyPolicy: {{ .Values.concurrencyPolicy }}
          volumes:
            - name: {{ $releaseName  }}-file-credentials-vol
              secret:
                secretName: "{{ $releaseName  }}-file-credentials"
            - name: dump-vol
              hostPath:
                path: /var/log/dumps/{{ .Release.Name }}
                type: DirectoryOrCreate

          containers:
            - name: {{ .Release.Name }}
              image: "{{ .Values.image }}"
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: {{ $releaseName  }}-file-credentials-vol
                  mountPath: /etc/credentialfiles/
                - mountPath: /var/log/dumps
                  name: dump-vol
              ports:
                  {{- range .Values.ports }}
                  {{- with . }}
                - name: {{ .name }}
                  containerPort: {{ .containerPort }}
                  protocol: TCP
                  {{- end }}
                  {{- end }}
              {{- if or .Values.podCPULimit .Values.podMemoryLimit }}
              resources:
                limits:
                {{- if .Values.podCPULimit }}
                  cpu: {{ .Values.podCPULimit }}
                {{- end}}
                {{- if .Values.podMemoryLimit }}
                  memory: {{ .Values.podMemoryLimit }}Gi
                {{- end}}
              {{- end }}
              env:
              {{- range $k, $v := .Values.configurations }}
              - name: {{ $k }}
                valueFrom:
                  secretKeyRef:
                    name: "{{ $releaseName }}-configs"
                    key: {{ $k }}
              {{- end }}
              {{- range $k, $v := .Values.credentials }}
              - name: {{ $k }}
                valueFrom:
                  secretKeyRef:
                    name: "{{ $releaseName }}-credentials"
                    key: {{ $k }}
              {{- end }}
          {{- if .Values.nodeSelector }}
          nodeSelector:
            environment: {{ .Values.nodeSelector }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{ toYaml . | indent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{ toYaml . | indent 8 }}
          {{- end }}