apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.environment }}-{{ .Values.zoneType }}-route53-dns-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.environment }}-{{ .Values.zoneType }}-route53-dns-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.environment }}-{{ .Values.zoneType }}-route53-dns-sa
    namespace: default