apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.environment }}-{{ .Values.zoneType }}-route53-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.environment }}-{{ .Values.zoneType }}-route53-dns
    spec:
      serviceAccountName: {{ .Values.environment }}-{{ .Values.zoneType }}-route53-dns-sa
      containers:
      - name: {{ .Values.environment }}-{{ .Values.aws.zoneType }}-route53-dns
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - --source=service
        - --zone-id-filter={{ .Values.zoneId }}
        - --provider=aws
        - --policy=upsert-only
        - --domain-filter={{ .Values.zoneDns }}
        - --aws-zone-type={{ .Values.zoneType }}
        - --registry=noop
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.environment }}-{{ .Values.zoneType }}-route53-dns-secrets
              key: AWS_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.environment }}-{{ .Values.zoneType }}-route53-dns-secrets
              key: AWS_SECRET_KEY
