{{- $releaseName := .Release.Name}}
{{- $crmModuleName := .Values.crmModuleName}}

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name  }}
  labels:
    app: {{ .Release.Name  }}
    chart: {{ template "capillary-base.chart" . }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.deploymentStrategy | default "RollingUpdate" }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
      annotations:
        deploymentId: {{ .Values.deploymentId }}
        buildId: {{ .Values.buildId }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
{{- if .Values.roleName }}
        iam.amazonaws.com/role: {{ .Values.roleName }}
{{- end }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image }}"
{{- if .Values.capabilities }}
          securityContext:
            capabilities:
              add:
              {{- range .Values.capabilities.add }}
              {{- with . }}
              - {{ . }}
              {{- end}}
              {{- end}}
              drop:
              {{- range .Values.capabilities.drop }}
              {{- with . }}
              - {{ . }}
              {{- end}}
              {{- end}}
  {{- end }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - {{ .Release.Name }}
                    topologyKey: kubernetes.io/hostname

          volumeMounts:
            - mountPath: /var/log/dumps
              name: dump-vol
            - name: {{ $releaseName  }}-file-credentials-vol
              mountPath: /etc/credentialfiles/
          {{- if gt (len .Values.ports) 0 }}
          ports:
              {{- range .Values.ports }}
              {{- with . }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: TCP
              {{- end }}
              {{- end }}
          {{- end }}
{{- if or .Values.podCPULimit .Values.podMemoryLimit }}
          resources:
            requests:
              {{- if .Values.podCPURequest }}
              cpu: {{ .Values.podCPURequest }}
              {{- end}}
              {{- if .Values.podMemoryRequest }}
              memory: {{ .Values.podMemoryRequest }}Gi
              {{- end}}
            limits:
            {{- if .Values.podCPULimit }}
              cpu: {{ .Values.podCPULimit }}
            {{- end}}
            {{- if .Values.podMemoryLimit }}
              memory: {{ .Values.podMemoryLimit }}Gi
            {{- end}}
{{- end }}
          env:
{{- range $k, $v := .Values.configurations }}
          - name: {{ $k }}
            valueFrom:
              secretKeyRef:
                name: "{{ $releaseName }}-configs"
                key: {{ $k }}
{{- end }}
{{- range $k, $v := .Values.credentials }}
          - name: {{ $k }}
            valueFrom:
              secretKeyRef:
                name: "{{ $releaseName }}-credentials"
                key: {{ $k }}
{{- end }}
{{- if .Values.enableLivenessTCP}}
{{- template "livenessTCP" . }}
{{- end }}
{{- if .Values.enableLivenessHTTP}}
{{- template "livenessHTTPGet" . }}
{{- end }}
{{- if .Values.enableReadinessTCP}}
{{- template "readinessTCP" . }}
{{- end }}
{{- if .Values.enableReadinessHTTP}}
{{- template "readinessHTTPGet" . }}
{{- end }}
{{- if .Values.isJmxEnabled }}
        - name: jmx
          image: "486456986266.dkr.ecr.us-west-1.amazonaws.com/ops/jmx-sidecar:b9daadf"
          imagePullPolicy: IfNotPresent
          env:
            - name: NRIA_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ $releaseName }}-configs"
                  key: NEWRELIC_KEY
          #            - name: NRIA_VERBOSE
          #              value: "1"
{{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
        environment: {{ .Values.nodeSelector }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if (semverCompare ">=1.14" .Capabilities.KubeVersion.GitVersion) }}
      enableServiceLinks: false
{{- end }}
      volumes:
        - name: dump-vol
          hostPath:
            path: /var/log/dumps/{{ .Release.Name }}
            type: DirectoryOrCreate
        - name: {{ $releaseName  }}-file-credentials-vol
          secret:
            secretName: {{ $releaseName  }}-file-credentials