apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name  }}-file-credentials"
type: Opaque
data:
  {{- range .Values.secretFileMounts }}
  {{- with . }}
  {{ .name }}: {{ .value }}
  {{- end }}
  {{- end }}