{{- $releaseName := .Release.Name}}
{{- $crmModuleName := .Values.crmModuleName}}

  apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name  }}
  labels:
    app: {{ .Release.Name  }}
    chart: {{ template "capillary-base.chart" . }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
      annotations:
        deploymentId: {{ .Values.deploymentId }}
        buildId: {{ .Values.buildId }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}
            topologyKey: kubernetes.io/hostname
      volumes:
        - name: dump-vol
          hostPath:
            path: /var/log/dumps
            type: Directory
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image }}"
{{- if .Values.capabilities }}
          securityContext:
            capabilities:
              add:
              {{- range .Values.capabilities.add }}
              {{- with . }}
              - {{ . }}
              {{- end}}
              {{- end}}
              drop:
              {{- range .Values.capabilities.drop }}
              {{- with . }}
              - {{ . }}
              {{- end}}
              {{- end}}
  {{- end }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
          ports:
              {{- range .Values.ports }}
              {{- with . }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: TCP
              {{- end }}
              {{- end }}
{{- if or .Values.podCPULimit .Values.podMemoryLimit }}
          resources:
            limits:
            {{- if .Values.podCPULimit }}
              cpu: {{ .Values.podCPULimit }}
            {{- end}}
            {{- if .Values.podMemoryLimit }}
              memory: {{ .Values.podMemoryLimit }}Gi
            {{- end}}
{{- end }}
          volumeMounts:
          - mountPath: /var/log/dumps
            name: dump-vol
          env:
{{- range $k, $v := .Values.configurations }}
          - name: {{ $k }}
            valueFrom:
              secretKeyRef:
                name: "{{ $releaseName }}-configs"
                key: {{ $k }}
{{- end }}
{{- range $k, $v := .Values.credentials }}
          - name: {{ $k }}
            valueFrom:
              secretKeyRef:
                name: "{{ $releaseName }}-credentials"
                key: {{ $k }}
{{- end }}
{{- template "crmConfigurations" . }}
{{- if .Values.enableLivenessTCP}}
{{- template "livenessTCP" . }}
{{- end }}
{{- if .Values.enableLivenessHTTP}}
{{- template "livenessHTTPGet" . }}
{{- end }}
{{- if .Values.enableReadinessTCP}}
{{- template "readinessTCP" . }}
{{- end }}
{{- if .Values.enableReadinessHTTP}}
{{- template "readinessHTTPGet" . }}
{{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
        environment: {{ .Values.nodeSelector }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
