apiVersion: v1
appVersion: 7.7.0
description: Filebeat - log parser
home: https://github.com/elastic/helm-charts
icon: https://helm.elastic.co/icons/beats.png
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: filebear-
sources:
- https://github.com/elastic/beats
version: 7.7.0
