apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: fluentd-efs
  name: fluentd-efs
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-efs
  template:
    metadata:
      labels:
        k8s-app: fluentd-efs
    spec:
      containers:
      - env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -v
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        name: fluentd-efs
        resources:
          limits:
            cpu: 800m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /host/lib
          name: libsystemddir
          readOnly: true
        - mountPath: /etc/fluent/config.d
          name: config-volume
          readOnly: true
        - mountPath: /var/log/efs/
          name: efsvol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluentd-efs
      serviceAccountName: fluentd-efs
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - hostPath:
          path: /usr/lib64
          type: ""
        name: libsystemddir
      - configMap:
          defaultMode: 420
          name: fluentd-efs-configs
        name: config-volume
      - name: efsvol
        persistentVolumeClaim:
          claimName: logs-efs-pvc
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 5
    type: RollingUpdate
