apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.environment }}-{{ .Values.aws.zoneType }}-route53-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app.environment }}-{{ .Values.aws.zoneType }}-route53-dns
    spec:
      serviceAccountName: route53-dns
      containers:
      - name: {{ .Values.app.environment }}-{{ .Values.aws.zoneType }}-route53-dns
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - --source=service
        - --zone-id-filter={{ .Values.aws.zoneId }}
        - --provider=aws
        - --policy=upsert-only
        - --aws-zone-type={{ .Values.aws.zoneType }}
        - --registry=noop
        env:
        - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: "IAM_CREDENTIALS"
                key: AWS_ACCESS_KEY
        - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: "IAM_CREDENTIALS"
                key: AWS_SECRET_KEY
