apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.environment }}-{{ .Values.zoneType }}-route53-dns-secrets
type: Opaque
data:
  AWS_ACCESS_KEY: {{ .Values.awsAccessKeyId | b64enc}}
  AWS_SECRET_KEY: {{ .Values.awsSecretAccessKey | b64enc}}