apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.environment }}-{{ .Values.aws.zoneType }}-route53-dns-secrets
type: Opaque
data:
  AWS_ACCESS_KEY: {{ .Values.aws.awsAccessKeyId | b64enc}}
  AWS_SECRET_KEY: {{ .Values.aws.awsSecretAccessKey | b64enc}}