# Default values for fluntd-es.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: 486456986266.dkr.ecr.us-west-1.amazonaws.com/crm/cap-transfer-logs:5fc8624

