# Default values for fluntd-es.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: gcr.io/google-containers/fluentd-elasticsearch:v2.0.1

nameOverride: ""
fullnameOverride: ""

cpuResourceLimit: 300m
memoryResourceLimit: 768Mi

