# Default values for capillary-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
serviceType: LoadBalancer

resources: {}

tolerations: []

affinity: {}