name: pre-commit
on:
  pull_request:
    branches: [tfdev]
jobs:
  pre-commit:
    runs-on: iac-arc
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # requites to grab the history of the PR
          fetch-depth: 0
      - name: Pre-commit check
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --color=always --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
