name: TF-CI-development-branch

on:
  push:
    branches:
      - tfdev
      - 'rc-*.*.*'
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch Name'
        required: true

jobs:
  build:
    runs-on: iac-arc

    steps:
      - name: Set BRANCH_NAME variable
        run: echo "BRANCH_NAME=${{ github.event.inputs.branchName || github.ref_name }}" >> $GITHUB_ENV
      - name: Checkout Facets-IAC code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
      - name: Extract POM version
        id: pom_version
        run: |
           POM_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
           echo "POM_VERSION=$POM_VERSION" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Extract POM Version, zip and upload to s3
        shell: bash
        id: run
        run: |
          POM_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
          mkdir archive
          zip -r archive/$POM_VERSION.zip capillary-cloud-tf
          aws s3 cp archive/$POM_VERSION.zip s3://${{ secrets.BUCKET_NAME }}/${{ env.BRANCH_NAME }}/$POM_VERSION.zip
          python .github/workflows/migrations/get_migrations.py capillary-cloud-tf/tfmain/scripts/migrations
          mv migrations.json archive/$POM_VERSION-migrations.json
          aws s3 cp archive/$POM_VERSION-migrations.json s3://${{ secrets.BUCKET_NAME }}/${{ env.BRANCH_NAME }}/$POM_VERSION-migrations.json
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
