name: TF-CI-development-branch

on:
  push:
    branches:
      - tfdev
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch Name'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set BRANCH_NAME variable
        run: echo "BRANCH_NAME=${{ github.event.inputs.branchName || 'tfdev' }}" >> $GITHUB_ENV
      - name: Checkout Facets-IAC code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -f capillary-cloud-tf/pom.xml clean install

      - name: Extract POM version
        id: pom_version
        run: |
           POM_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
           echo "POM_VERSION=$POM_VERSION" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}


      - name: Zip with POM_VERSION
        shell: bash
        id: run
        run: |
          mkdir -p archive
          zip -r archive/${{ steps.pom_version.outputs.POM_VERSION }}.zip capillary-cloud-tf

      - name: Upload file to bucket
        uses: zdurham/s3-upload-github-action@master
        env:
          FILE: 'archive/${{ steps.pom_version.outputs.POM_VERSION }}.zip'
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.BUCKET_NAME }}
          S3_KEY: '${{ env.BRANCH_NAME }}/${{ steps.pom_version.outputs.POM_VERSION }}.zip'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
